name: Linting, testing, building
on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-verison: [ 17.x ]
    steps: 
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-verison }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install --force
      - name: build production project
        if: always()
        run: npm run build:prod
      - name: linting typescript
        if: always()
        run: npm run lint:ts
      - name: linting css
        if: always()
        run: npm run lint:css
      - name: unit testing
        if: always()
        run: npm run test:unit
      - name: build storybook
        if: always()
        run: npm run storybook:build
      - name: screenshot tests
        if: always()
        run:  npm run test:ui:ci
      
      