name: Linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-verison: [ 17.x ]
    steps: 
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ marix.node-verison }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:css
      - name: unit testing
        run: npm run test:unit
      
      